title: Leetcode Curriculum

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  date_format: "%b %-d, %Y"

# this is the header on top of every page
header_pages:
  - pages/lists/blind100.md
  - pages/journal.md

# this lets you access it on your local area network
host: 0.0.0.0


collections:
  problems:
    output: true